language: python

dist: xenial

# Check against N & N-1 Spark versions
env:
  - SPARK_VERSION=2.4.0
  - SPARK_VERSION=2.4.1

python:
  - "3.6"
  - "3.7"

addons:
  apt:
    packages:
      - axel
  sonarcloud:
    organization: "astrolabsoftware"
    token:
      secure: "TZcfIrklGm+rrDHxVz4EqqJRV7xr3N+bH3AejlNxCFqbnuOpumXANhaSKgX8nZHHGuT19idgVICQ8Ywq2t6RVkwjgJY1MTVfcx4AtuOm15KW86QhbBaXGAWLUhp7Jpm93a+2DXjXnhldjFxCkhamGF2R/H3Wejye+as8T4raPvOU8+yQXBCxJSRFEQt4yJQyuvNCZZvY19Q7OEO7bYlFXeCv+0W9afwKhExmuE4BqVEHgYwyebO06aptzmOi860zfjQNqeDRMa1oosuVNPNd4QpBnDi+7LNjvWyn174OfapVNMF1KaNRPPMXJ6COI/GVy3bN8mjfApY7RRpsHpxVQQ/0VDLfUFVXDBHna79STxliDKnZDedl0T0mCVokD5w+hNxFEkbYi51fXVjlQV1hx15/kk4/u09CtBy6PaA9rjyHNzF4gC2eEMHqhZFASKFjNLslixwdjT+2pylGLnBKQGNFk2zFZeEJ6+XmKWUBRLzH1OImSh/JDtUZxqJ74JaQUrQkcYjPqIr/K9aeoYiuZa8iMYOBBcbCw9s1Cj+Hn3Kn6jGvyBgccDl9puQvV7U8adkcKfSLxEz9c5Wxqt0Q0sFO9MRHK9a55e7XVD5AuyUcRd44iFYR3csZ52vMmQtbtgKB4hVO94OCp22coAC0KO9f5dEUWDgX88M77RdR4Kw="

before_install:
  - export FINK_HOME="/home/travis/build/astrolabsoftware/fink-broker"
  # Install Java 8 for Xenial
  - source conf/java8_for_xenial.sh
  - export PATH=$HOME/.local/bin:${FINK_HOME}/bin:$PATH
  # Download data used for the test suite
  - cd datasim; ./download_ztf_alert_data.sh; cd ..

install:
  # Download spark
  - "[ -f spark ] || mkdir spark && cd spark && axel http://archive.apache.org/dist/spark/spark-${SPARK_VERSION}/spark-${SPARK_VERSION}-bin-hadoop2.7.tgz && cd .."
  - tar -xf ./spark/spark-${SPARK_VERSION}-bin-hadoop2.7.tgz
  - export SPARK_HOME=`pwd`/spark-${SPARK_VERSION}-bin-hadoop2.7
  - echo "spark.yarn.jars=${SPARK_HOME}/jars/*.jar" > ${SPARK_HOME}/conf/spark-defaults.conf
  - echo "spark.python.daemon.module coverage_daemon" > ${SPARK_HOME}/conf/spark-defaults.conf
  - export SPARKLIB=${SPARK_HOME}/python:${SPARK_HOME}/python/lib/py4j-0.10.7-src.zip
  - export PYTHONPATH="${SPARKLIB}:${FINK_HOME}:${FINK_HOME}/python:$PYTHONPATH"
  - export PATH="${SPARK_HOME}/bin:${SPARK_HOME}/sbin:${PATH}"

  # Python deps
  - pip install --upgrade pip setuptools wheel
  - pip install -r requirements.txt

script:
  # For sonar to run correctly
  - git fetch --unshallow --quiet

  # Execute tests and report coverage
  - fink start simulator -c ${FINK_HOME}/conf/fink.conf.travis
  - fink_test
  - bash <(curl -s https://codecov.io/bash)

  # Scan with sonarqube
  - coverage xml -i
  - sonar-scanner
