language: python

dist: xenial

python:
  - "3.6"
  - "3.7"

addons:
  apt:
    packages:
      - axel
      - oracle-java8-installer
  sonarcloud:
    organization: "astrolabsoftware"
    token:
      secure: ${SONAR_KEY}

before_install:
  - export PATH=$HOME/.local/bin:$PATH

install:
  # Download spark 2.4.0
  - "[ -f spark ] || mkdir spark && cd spark && axel http://www-us.apache.org/dist/spark/spark-2.4.0/spark-2.4.0-bin-hadoop2.7.tgz && cd .."
  - tar -xf ./spark/spark-2.4.0-bin-hadoop2.7.tgz
  - export SPARK_HOME=`pwd`/spark-2.4.0-bin-hadoop2.7
  - echo "spark.yarn.jars=${SPARK_HOME}/jars/*.jar" > ${SPARK_HOME}/conf/spark-defaults.conf
  - echo "spark.python.daemon.module coverage_daemon" > ${SPARK_HOME}/conf/spark-defaults.conf

  # Python deps
  - pip install --upgrade pip setuptools wheel
  - pip install -r requirements.txt

script:
  # Scan with sonarqube
  - sonar-scanner

  # Execute tests and report coverage
  - export FINK_HOME="/home/travis/build/astrolabsoftware/fink-broker"
  - export SPARKLIB=${SPARK_HOME}/python:${SPARK_HOME}/python/lib/py4j-0.10.7-src.zip
  - export PYTHONPATH="${SPARKLIB}:${FINK_HOME}:${FINK_HOME}/python:$PYTHONPATH"
  - ./coverage_and_test.sh
  - bash <(curl -s https://codecov.io/bash)
