language: python

python:
  - "3.6"
  - "3.7"

addons:
  apt:
    packages:
      - axel

before_install:
  - export PATH=$HOME/.local/bin:$PATH
  - pip install --user codecov coverage

install:
  # Download spark 2.4.0
  - "[ -f spark ] || mkdir spark && cd spark && axel http://www-us.apache.org/dist/spark/spark-2.4.0/spark-2.4.0-bin-hadoop2.7.tgz && cd .."
  - tar -xf ./spark/spark-2.4.0-bin-hadoop2.7.tgz
  - export SPARK_HOME=`pwd`/spark-2.4.0-bin-hadoop2.7
  - echo "spark.yarn.jars=$SPARK_HOME/jars/*.jar" > $SPARK_HOME/conf/spark-defaults.conf

  # Python deps
  - pip install --upgrade pip setuptools wheel
  - pip install -r requirements.txt

script:
  - export FINK_HOME="/home/travis/build/astrolabsoftware/fink-broker"
  - export PYTHONPATH="$FINK_HOME:$FINK_HOME/python:$PYTHONPATH"
  - ./coverage_and_test.sh

after_success:
  coveralls
