site_name: Fink
repo_url: https://github.com/astrolabsoftware/fink-broker
edit_uri: ""

nav:
    - Home: index.md
    - User Guide:
      - Infrastructure: user_guide/infrastructure.md
      - Configuration: user_guide/configuration.md
      - Available services: user_guide/available-services.md
      - Simulating streams: user_guide/simulator.md
      - Testing Fink: user_guide/testing-fink.md
      - Adding a new service: user_guide/adding-new-service.md
      - webUI: user_guide/dashboard.md
    - About:
      - Release Notes: release-notes.md
      - Contributing: contributing.md
      - License: license.md

# theme: readthedocs

copyright: Copyright &copy; 2018-19 <a href="https://astrolabsoftware.github.io/">AstroLab Software</a>.
